### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by DeerMaximum** [farthinder/Proxmox-Encrypted-Remote-Backup#2]
When I start the backup it will show the following error:
```
INFO: Traceback (most recent call last):
INFO:   File "/opt/scripting/encryptedRemoteBackup/ProxmoxEncryptedBackup.py", line 118, in <module>
INFO:     outputFilename = re.search("vzdump-qemu-(.*)\.\w*?$", index["tarfile"])[1]
INFO: TypeError: 'NoneType' object is not subscriptable
```

How do I solve the problem?

Full Log:

```
INFO: starting new backup job: vzdump 104 --compress lzo --script /opt/scripting/encryptedRemoteBackup/ProxmoxEncryptedBackup.py --quiet 1 --storage LocalBackup --all 0 --mailnotification failure --mode snapshot --node homerserver
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Phase:job-start
INFO: CryptBackup - INFO - Creating new job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: Starting Backup of VM 104 (lxc)
INFO: Backup started at 2020-04-25 22:43:46
INFO: status = running
INFO: CT Name: Pihole
INFO: backup mode: snapshot
INFO: ionice priority: 7
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Phase:backup-start
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Updating existing job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Phase:pre-stop
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Updating existing job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: create storage snapshot 'vzdump'
  Logical volume "snap_vm-104-disk-0_vzdump" created.
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Phase:pre-restart
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Updating existing job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Phase:post-restart
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Updating existing job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: creating archive '/mnt/pve/LocalBackup/dump/vzdump-lxc-104-2020_04_25-22_43_46.tar.lzo'
INFO: Total bytes written: 1659904000 (1.6GiB, 140MiB/s)
INFO: archive file size: 638MB
INFO: delete old backup '/mnt/pve/LocalBackup/dump/vzdump-lxc-104-2020_04_25-22_42_30.tar.lzo'
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Phase:backup-end
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Updating existing job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: remove vzdump snapshot
  Logical volume "snap_vm-104-disk-0_vzdump" successfully removed
INFO: Finished Backup of VM 104 (00:00:13)
INFO: Backup finished at 2020-04-25 22:43:59
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Phase:log-end
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Updating existing job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Phase:job-end
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Updating existing job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - The backup job has ended successfully, will prepare to encrypt
INFO: Traceback (most recent call last):
INFO:   File "/opt/scripting/encryptedRemoteBackup/ProxmoxEncryptedBackup.py", line 118, in <module>
INFO:     outputFilename = re.search("vzdump-qemu-(.*)\.\w*?$", index["tarfile"])[1]
INFO: TypeError: 'NoneType' object is not subscriptable
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Phase:job-abort
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
INFO: CryptBackup - INFO - Updating job file:/opt/scripting/encryptedRemoteBackup/jobs/31315.job
ERROR: Backup job failed - command '/opt/scripting/encryptedRemoteBackup/ProxmoxEncryptedBackup.py job-end' failed: exit code 1
TASK ERROR: command '/opt/scripting/encryptedRemoteBackup/ProxmoxEncryptedBackup.py job-end' failed: exit code 1
```

**Comment by farthinder** [comment]
Hey!
Thanks for trying out this!

I will need the debug log to be able to troubleshoot this, it should be available here /opt/scripting/encryptedRemoteBackup/output.log


It looks like it´s having trouble finding what files to encrypt, can you also give me the job file for the corresponding log?
The file should be here: /opt/scripting/encryptedRemoteBackup/jobs/

**Comment by DeerMaximum** [comment]
Here are the files
[logs.zip](https://github.com/farthinder/Proxmox-Encrypted-Remote-Backup/files/4547473/logs.zip)

**Comment by farthinder** [comment]
Thanks!

Looks like you are taking backup of containers which have a different name standard then VMs and as I don't use containers I haven't run in to this problem.

Could you confirm by running the backup job only with VMs while I look at a fix?

**Comment by farthinder** [comment]
@DeerMaximum I believe I found the bug, if you like you can try running the latest commit and report back your findings.

**Comment by DeerMaximum** [comment]
Now the script crashes without an error. With a normal VM the script works.
[logs.zip](https://github.com/farthinder/Proxmox-Encrypted-Remote-Backup/files/4548073/logs.zip)

**Comment by farthinder** [comment]
Hm, I cant reproduce that problem. What errors are visible in the backup job shown in the GUI?
Do you happen to know if that output is in a file somewhere?

**Comment by DeerMaximum** [comment]
I have found the error.

```
INFO: starting new backup job: vzdump 104 --compress lzo --script /opt/scripting/encryptedRemoteBackup/ProxmoxEncryptedBackup.py --quiet 1 --storage LocalBackup --all 0 --node homerserver --mailnotification always --mode snapshot
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Phase:job-start
INFO: CryptBackup - INFO - Creating new job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: Starting Backup of VM 104 (lxc)
INFO: Backup started at 2020-05-01 12:59:08
INFO: status = running
INFO: CT Name: Pihole
INFO: backup mode: snapshot
INFO: ionice priority: 7
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Phase:backup-start
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Updating existing job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Phase:pre-stop
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Updating existing job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: create storage snapshot 'vzdump'
  Logical volume "snap_vm-104-disk-0_vzdump" created.
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Phase:pre-restart
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Updating existing job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Phase:post-restart
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Updating existing job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: creating archive '/mnt/pve/LocalBackup/dump/vzdump-lxc-104-2020_05_01-12_59_08.tar.lzo'
INFO: Total bytes written: 1669816320 (1.6GiB, 128MiB/s)
INFO: archive file size: 641MB
INFO: delete old backup '/mnt/pve/LocalBackup/dump/vzdump-lxc-104-2020_04_28-21_24_00.tar.lzo'
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Phase:backup-end
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Updating existing job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: remove vzdump snapshot
  Logical volume "snap_vm-104-disk-0_vzdump" successfully removed
INFO: Finished Backup of VM 104 (00:00:14)
INFO: Backup finished at 2020-05-01 12:59:22
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Phase:log-end
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Updating existing job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Phase:job-end
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Updating existing job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - The backup job has ended successfully, will prepare to encrypt
INFO: Traceback (most recent call last):
INFO:   File "/opt/scripting/encryptedRemoteBackup/ProxmoxEncryptedBackup.py", line 146, in <module>
INFO:     threadPool = ThreadPoolExecutor(max_workers=Settings.threads)
INFO: AttributeError: module 'ProxmoxEncryptedBackupSettings' has no attribute 'threads'
INFO: CryptBackup - INFO - Encrypted BackupScript called
INFO: CryptBackup - INFO - Job File:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Phase:job-abort
INFO: CryptBackup - INFO - Parsing existing job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
INFO: CryptBackup - INFO - Updating job file:/opt/scripting/encryptedRemoteBackup/jobs/28852.job
ERROR: Backup job failed - command '/opt/scripting/encryptedRemoteBackup/ProxmoxEncryptedBackup.py job-end' failed: exit code 1
TASK ERROR: command '/opt/scripting/encryptedRemoteBackup/ProxmoxEncryptedBackup.py job-end' failed: exit code 1
```

**Comment by KorewaKiyo** [comment]
What's the value for ```threads=``` in your settings file?

**Comment by DeerMaximum** [comment]
gpgThreads=1
rcloneThreads=5

**Comment by KorewaKiyo** [comment]
Looking through the source, there's no specific gpg or rclone threads, just the ```threads``` value, try with just that value

**Comment by DeerMaximum** [comment]
That fixed the bug. Thanks
